export const ErrorCodes = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASE_ERROR: 3,
    ADD_PRODUCT_TO_CART_ERROR: 4,
    ADD_CART_ERROR: 5,
    GET_PRODUCTS_FROM_CART_ERROR: 6,
    ADD_USER_ERROR: 7,
    GET_USER_ERROR: 8,
    ADD_PRODUCT_ERROR: 9,
    GET_PRODUCT_ERROR: 10,
}